# This is a basic workflow to help you get started with Actions

name: Lint Test CFN templates

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Cloudformation-checker:
    name: Check linting and securtity concerns
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: cfn-lint-action
        uses: ScottBrenner/cfn-lint-action@v2.2.3
        with:
          args: "*.yaml"
      
      - name: cfn-nag-action
        uses: minchao/cfn-nag-action@v0.1
