# This workflow takes the AWS CloudFormation files zips them together.  Then pushes/uploads them to the Octopus Instance specified. 
# Within the repo's secrets are the information relating to the Octopus Instance URL, API key and Space. 

name: S3 Bucket
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - S3Bucket



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "S3AWS-CloudFormation"
  S3AWS-CloudFormation:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
    # This first step takes the code within the Repo and pulls it into the workspace
    - uses: actions/checkout@v2
    # We install the latest version of Octopus CLI
    - uses: OctopusDeploy/install-octopus-cli-action@v1.1.8

    # We take the files inside the CloudFormation folder and zip them together
    - name: Zip CloudFormation files
      run: octo pack --id="S3BucketTemplate" --format="zip" --version=${{ github.run_number }} --basePath=${{ github.workspace }}\S3Bucket\ --outFolder=${{ github.workspace }}\output
    # We take the zip file we created and push them to the Octopus Deploy server instance
    - name: Push CloudFormation files
      run: octo push --package="${{ github.workspace }}\output\S3BucketTemplate.${{ github.run_number }}.zip" --server="${{ secrets.OCTOPUSSERVERURL }}" --apiKey="${{ secrets.OCTOPUSSERVERAPIKEY }}" --space="${{ secrets.OCTOPUSSERVER_SPACE }}"
